@startuml
left to right direction
skinparam packageStyle Frame
package usecase {
actor "Сотрудник логистического отдела" as sotr
actor "Пользователь \n    {abstract}" as user
actor "База данных" as bd
user <|- sotr
rectangle {
 user -- (Авторизация)
 sotr -- (Выбор задачи)
 (Формирование плана отгрузок готовой \n продукции заказчикам на месяц) as z1
 (Формирование суточно-недельного \n графика доставки готовой продукции) as z2
 (Формирование требования на подачу транспортных средств) as z3
 (Формирование рационального маршрута \n движения транспортных средств при доставке продукции) as z4
 (Выбор задачи) ..> z1 : <<include>>
 (Выбор задачи) ..> z2 : <<include>>
 (Выбор задачи) ..> z3 : <<include>>
 (Выбор задачи) ..> z4: <<include>>
 bd -u-- z1
 bd -u-- z2
 bd -u-- z3
 bd -u-- z4
 bd -d- (Авторизация)

 }
}
@enduml