@startuml
'https://plantuml.com/activity-diagram-beta


|abstr| Пользователь
|user| Сотрудник ПЭО

|abstr|

start
->[Отрытие сайта];
repeat
    :Открыть страницу авторизации;
    -> [Отрытие страницы авторизации];
    if (Сайт закрыт?) then (нет)
    else (да)
        stop
    endif  
    :Ввести данные;
    -> [Данные введены];
    
|sys| Система
    :Найти данные пользователя в БД;
    
|bd| СУБД MySql
    :Поиск пользователя в БД;
    
|sys| Система
    :Сравнение данных;
    backward :Вывод ошибки;
    repeat while(Авторизация пройдена?) is (нет) not (да)
    :Открыть страницу выбора отдела;


|user|
      -> [Cтраницы выбора отдела открыта];
      :Выбрать планово-экономический отдел;
       if (Пользователь закрыл сайт?) then (нет)
          else (да)
              stop
          endif  

|sys| 
        (b)
        :Открыть страницу выбора типа документа;
        ->[Страница открыта];
|user|
        :Выбрать документ "Формирование ежемесячного плана\n выпуска изделий в номенклатуре";
        -> [Документ выбран];
        'label ff;
        :Нажать кнопку "Создать новый документ";
        -> [Кнопка нажата];
|sys|         
        :Получить названия документов из БД;
        
|bd|    
        :Сделать выборку названий нужных документов;
        
|sys| 
        :Подгрузить данные;        
|user|
        :Выбрать документы из представленных;
        -> [Документы выбраны];
        
        :Нажать кнопку "Создать";
        'validate
        -> [Кнопка нажата];
|sys| 
        :Получить все нужные документы из БД;
|bd|    
        :Сделать выборку нужных документов;
|sys|
        :Валидация данных;
        if("Валидация пройдена?") then (да)
        else (нет)
            :Вывод ошибки;
            (b)
            detach
        endif
	    fork
            :Определить ограничения;
        fork again
            :Определить целевую функцию;
        end fork
        :Расчитать задачу;
        ->[Расчёт произведён];
        :Записать данные в БД;
|bd|    
        :Вставка данных в таблицу;
        
|sys|
        (a)
        :Вывести документ на экран;
                 
|user|    
        :Документ;    
       
     ->[Документ выведен];


        if (Пользователь выбрал экспорт документа?) then (да)
|sys|
            :Экспорт документа;
            ->[Документ экспортирован];
            
        else (нет)    
        endif  
|user|         
         if (Пользователь нажал "Вернуться к докуметам отдела?") then (нет)
          else (да)
               (b)
               detach
          endif 
         if (Пользователь закрыл сайт?) then (нет)
            else (да)
                stop
            endif 
       (a)
       detach    
@enduml
