@startuml
!define ABSTRACT {abstract}
!define include <<include>>
!define extend <<extend>>

skinparam defaultTextAlignment center

frame "use case" {
'left to right direction

:Пользователь\n ABSTRACT : as abstr
:Сотрудник ПЭО: as employee
:База данных: as bd

employee -l-|> abstr

rectangle "Программа" {
    usecase data_write as "Запись данных"
    '--
    'extension points:
    'Экспорт документа"
    usecase (Чтение данных) as data_read
    usecase (Авторизация\nABSTRACT) as autorization
    usecase (Выбор документа) as choose
    usecase (Формирование ежемесячного плана\n выпуска изделий в номенклатуре) as task1
    usecase (Формирование отчёта сравнения плановых\n и фактических технико-экономических показателей) as task2
    usecase (Формирование отчёта о себестоимости\n единицы продукции) as task3
    usecase (Формирование отчёта о рентабельности\n за месяц) as task4
    usecase (Экспорт полученного\n документа) as show_data
    'note "condition:\n{пользователь нажал\nна кнопку экспорта документа}\nextension point:\nЭкспорт документа" as N2
    
   
    usecase (Выбор нужных документов) as select
     'usecase (Наж) as button
    usecase validation as  "Валидация данных"
    '--
   ' extension points:
    'Вывод сообщения об ошибке"
    usecase (Расчёт) as solve
    'usecase (Вывод сообщения об ошибке) as notvalid
     'note "condition:\n{валидация не прошла}\nextension point:\nВывод сообщения об ошибке" as N3
    
    'data_write .. N2
    'N2 .. show_data
    abstr -- autorization
    bd -r- data_read
    bd -- data_write
    autorization -.> data_read : include
    employee -- choose 
    choose -r.> task1: include
    choose --.> task2: include
    choose -.> task3: include
    choose -.> task4: include
    'task1 -.> data_write : include
    task2 -.> data_write : include
    task3 -.> data_write : include
    task4 -.> data_write : include
    show_data -d.> data_write : extend
    
    'task1 -.> solve : include
    task1 -r.> select : include
    
    

    employee -- select
    
    select -.> validation : include
    validation -r.> solve : include
    solve -l.> data_write : include
    'notvalid -u.> validation : extend
    'notvalid .. N3
    'N3 .. validation
}
}

@enduml
